
pod:
 containerName: "container"
 imageName: ""
 containerPort: 80

services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  devAppPort: 8081
  uatAppPort: 8082
  prodAppPort: 8085
  nodeDevAppPort: 30547


environment: ""

config: 
  name: app-container-config
  volume: app-container-config-vol
  mountPath: config


