
pod:
 containerName: "container"
 imageName: ""
 containerPort: 80
 volume: config-vol-2

services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  devAppPort: 8081
  uatAppPort: 8082
  prodAppPort: 8085

environment: ""

config: app-container-config
